image: node:14.16.1

cache:
    paths:
        - node_modules/
        - out/
        - .next/

deploy-dev:
    stage: deploy
    script:
        - export AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID
        - export AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY
        - export APP_DISTRIBUTION_ID=$DEV_APP_DISTRIBUTION_ID
        - export APP_S3_BUCKET=$DEV_APP_S3_BUCKET
        - export STORYBOOK_DISTRIBUTION_ID=$DEV_STORYBOOK_DISTRIBUTION_ID
        - export STORYBOOK_S3_BUCKET=$DEV_STORYBOOK_S3_BUCKET
        - export APP_ENV=development
        - npm install
        - npm run deploy
    only:
        - dev

deploy-prod:
    stage: deploy
    script:
        - export AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID
        - export AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY
        - export DISTRIBUTION_ID=$PROD_DISTRIBUTION_ID
        - export APP_S3_BUCKET=$PROD_APP_S3_BUCKET
        - export STORYBOOK_DISTRIBUTION_ID=$PROD_STORYBOOK_DISTRIBUTION_ID
        - export STORYBOOK_S3_BUCKET=$PROD_STORYBOOK_S3_BUCKET
        - export APP_ENV=production
        - npm install
        - npm run deploy
    only:
        - tags