image: node:14.16.1

cache:
    paths:
        - node_modules/

build-test:
    stage: test
    script:
        - npm install
        - npm run export
        - npm run build-storybook
    only:
        - merge_requests
