name: Node.js CI

on:
    push:
        tags: [ * ]

jobs:
    build:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
                node-version: ${{ matrix.node-version }}

        - run: export AWS_ACCESS_KEY_ID=${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
        - run: export AWS_SECRET_ACCESS_KEY=${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
        - run: export APP_DISTRIBUTION_ID=${{ secrets.PROD_APP_DISTRIBUTION_ID }}
        - run: export APP_S3_BUCKET=${{ secrets.PROD_APP_S3_BUCKET }}
        - run: export STORYBOOK_DISTRIBUTION_ID=${{ secrets.PROD_STORYBOOK_DISTRIBUTION_ID }}
        - run: export STORYBOOK_S3_BUCKET=${{ secrets.PROD_STORYBOOK_S3_BUCKET }}
        - run: export APP_ENV=production
        - run: npm install
        - run: npm run deploy

        env:
            CI: true